# Generated by Django 5.2.5 on 2026-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitations_student_bfb7dd_idx',
            old_name='invitations_student_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invitation',
            new_name='invitations_company_978be6_idx',
            old_name='invitations_company_status_idx',
        ),
    ]
