# Generated by Django 5.2.5 on 2026-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_task_id_6dc8c0_idx',
            old_name='submissions_task_status_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_student_6bcf5e_idx',
            old_name='submissions_student_date_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_sector_596a45_idx',
            old_name='tasks_sector_status_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_deadlin_7f16a6_idx',
            old_name='tasks_deadline_idx',
        ),
    ]
