# Generated by Django 5.2.5 on 2026-04-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nikoscore', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='nikoscoreevent',
            new_name='nikoscore_e_student_498e93_idx',
            old_name='nikoscore_events_student_date_idx',
        ),
    ]
